server:
  port: 8080

spring:
  main:
    web-application-type: reactive
easychat:
  auth:
    excludePaths:
      - /user
      - /user/register
      - /user/checkCode
      - /hi
    includePaths:
    adminPaths:
      - /admin/**