spring:
  datasource:
    url: jdbc:mysql://172.23.80.100:3306/easychat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 172.23.80.100
    port: 6379
redisson:
  address: "redis://172.23.80.100:6379"