spring:
  application:
    name: EasyChat-common
  datasource:
    url: jdbc:mysql://8.136.10.7:3306/easychat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 8.136.10.7
    port: 6379
redisson:
  address: "redis://8.136.10.7:6379"

# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键类型 AUTO:数据库自增 INPUT:手动输入
      id-type: auto
      # 逻辑删除配置
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1       # 逻辑已删除值
      logic-not-delete-value: 0   # 逻辑未删除值
  # mapper.xml文件位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.easychat.common.entity.po
